# Javascript Node CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11@sha256:af0ffb60afc34736f30fd8ce6662175ca29009835308fb7786e27ecfce424f20
        environment:
          TEST_FFLAMINGO_DATABASE_URL: postgresql://fflamingo_user@localhost/fflamingo_test

      # Specify service dependencies here if necessary
      # images: https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
      - image: circleci/postgres:9.6-alpine-ram@sha256:5ebd728525a6d16fd8c1581e85435ca7a9febed1d6e96e9c02e1632f8ce7e3fc
        environment:
          POSTGRES_USER: fflamingo_user
          POSTGRES_DB: fflamingo_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          - v2-dependencies-

      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run:
          name: run jest tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

      # upload cov!
      - run:
          name: coverage
          command: yarn coverage

      # store artifacts
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
